### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by SandroMiguel** [rsn86/MWB-DBDocPy#1]
This plugin still works today (MySQL Workbench 6.3.8) ?
After installing the plugin how can I use them?

**Comment by rsn86** [comment]
This plugin was for an older version. Look at http://tmsanchezdev.blogspot.com.br/2015/03/html-report-from-mysqlworkbench-6x.html for a plugin compatible with version 6.x.

**Comment by SandroMiguel** [comment]
Now it works. Thank you!
